npm:
	mkdir -p ~/.config/stockminer/bin
	mkdir -p ~/.config/stockminer/etc
	mkdir -p ~/.config/stockminer/data/stocks
	mkdir -p ~/.config/stockminer/www
	mkdir -p ~/.config/stockminer/src/website
	cp bin/stockminer ~/.config/stockminer/bin
	cp stocks/*.TXT ~/.config/stockminer/data/stocks
	cp etc/* ~/.config/stockminer/etc
	cp www/* ~/.config/stockminer/www
	cp main.js ~/.config/stockminer/
	cp *.json ~/.config/stockminer/
	cp -rp src/website ~/.config/stockminer/src
